# Google App Engine configuration for ISOLAB Agri Support
runtime: python39

# Service configuration
service: default

# Instance class (F1 = free tier, F2/F4 = more powerful)
instance_class: F2

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6
  min_instances: 1
  max_instances: 10

# Environment variables
env_variables:
  FLASK_ENV: production
  FLASK_DEBUG: False
  SECRET_KEY: your-secret-key-here
  GOOGLE_CLOUD_PROJECT: isolab-467911

# Static file handlers
handlers:
  # Static files
  - url: /static
    static_dir: static
    secure: always

  # Favicon
  - url: /favicon\.ico
    static_files: static/favicon.ico
    upload: static/favicon\.ico
    secure: always

  # All other routes handled by Flask app
  - url: /.*
    script: auto
    secure: always

# Skip uploading unnecessary files
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?__pycache__/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.pytest_cache/.*$
  - ^(.*/)?test_.*\.py$
  - ^(.*/)?.*_test\.py$
  - ^(.*/)?venv/.*$
  - ^(.*/)?env/.*$
  - ^(.*/)?\.env$
  - ^(.*/)?requirements-dev\.txt$

# Additional configuration
includes:
  - env_variables.yaml  # Optional: for sensitive environment variables